/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShortCategoryinBook } from './ShortCategoryinBook';
import {
    ShortCategoryinBookFromJSON,
    ShortCategoryinBookFromJSONTyped,
    ShortCategoryinBookToJSON,
    ShortCategoryinBookToJSONTyped,
} from './ShortCategoryinBook';

/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    name: string;
    /**
     * 
     * @type {ShortCategoryinBook}
     * @memberof Book
     */
    kind: ShortCategoryinBook;
}

/**
 * Check if a given object implements the Book interface.
 */
export function instanceOfBook(value: object): value is Book {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function BookFromJSON(json: any): Book {
    return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Book {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'kind': ShortCategoryinBookFromJSON(json['kind']),
    };
}

  export function BookToJSON(json: any): Book {
      return BookToJSONTyped(json, false);
  }

  export function BookToJSONTyped(value?: Book | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'kind': ShortCategoryinBookToJSON(value['kind']),
    };
}

