/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Short version of the category
 * @export
 * @interface ShortCategoryinBook
 */
export interface ShortCategoryinBook {
    /**
     * 
     * @type {number}
     * @memberof ShortCategoryinBook
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ShortCategoryinBook
     */
    name: string;
}

/**
 * Check if a given object implements the ShortCategoryinBook interface.
 */
export function instanceOfShortCategoryinBook(value: object): value is ShortCategoryinBook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ShortCategoryinBookFromJSON(json: any): ShortCategoryinBook {
    return ShortCategoryinBookFromJSONTyped(json, false);
}

export function ShortCategoryinBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortCategoryinBook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ShortCategoryinBookToJSON(json: any): ShortCategoryinBook {
    return ShortCategoryinBookToJSONTyped(json, false);
}

export function ShortCategoryinBookToJSONTyped(value?: ShortCategoryinBook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

